version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - aws-elastic-beanstalk/deploy:
          environment-song: musicee-dev
          application-song: musicee-backend
          filters:
            branches:
              only:
                - main